# Generated by Django 4.2.4 on 2023-08-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='changed_date',
            new_name='changed_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
